from django.urls import path
from todoapp import views
urlpatterns = [
	path('',views.index_view),
	path('index/',views.index_view),
	path('signup/',views.signup_view),
	path('actact/',views.account_activation_view),
	path('profile/',views.profile_view),
	path('showtodos/',views.showtodos_view),
	path('dashboard/',views.dashboard_view),
	path('sendotp/',views.sendotp_view),
	path('checkotp/',views.checkotp_view),
	path('changetitle/',views.changetitle_view),
	path('deltodo/',views.delete_view),
	path('savetextnote/',views.savetextnote_view),
	path('savechecklist/',views.savechecklist_view),
	path('getallpoints/',views.getallpoints_view),
	path('set_point/',views.setpoint_view),
	path('active_point/',views.activepoint_view),
	path('connects/',views.show_connect_view),
	path('searchuser/',views.search_user_view),
	path('userdetail/',views.user_detail_view),
	path('startconnection/',views.startconnection_view),
	path('changeconstatus/',views.changeconnectionstatus_view),
	path('collectinvites/',views.collect_invite_view),
	path('collectallconnections/',views.collect_allconnect_view),
	path('sharetodo/',views.sharetodo_view),
	path('activerecords/',views.activerecords_view),
	path('allsharedrecs/',views.sharedrecords_view),
	path('activenewinvites/',views.newinvites_view),
	path('myprofile/',views.myprofile_view),
]